export enum WINDOW_EVENT_TYPE {
  PLATFORM = 'PLATFORM',
  QUIT = 'QUIT',
  MINIMIZE = 'MINIMIZE',
  FULLSCREEN = 'FULLSCREEN',
  FLOAT = 'FLOAT',
  TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN',
  CLOSE_TAB_OR_WINDOW = 'CLOSE_TAB_OR_WINDOW',
  OPEN_EXTERNAL_LINK = 'OPEN_EXTERNAL_LINK'
}
