export enum WINDOW_EVENT_TYPE {
  FLOAT = 'FLOAT',
  FULLSCREEN = 'FULLSCREEN',
  CLOSE_TAB_OR_WINDOW = 'CLOSE_TAB_OR_WINDOW',
  MINIMIZE = 'MINIMIZE',
  OPEN_EXTERNAL_LINK = 'OPEN_EXTERNAL_LINK',
  PLATFORM = 'PLATFORM',
  QUIT = 'QUIT',
  EXPORT_GAME_START = 'EXPORT_GAME_START',
  EXPORT_GAME_PROCESSING = 'EXPORT_GAME_PROCESSING',
  EXPORT_GAME_COMPLETE = 'EXPORT_GAME_COMPLETE',
  TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN',
  SAVE_ASSET = 'SAVE_ASSET',
  GET_ASSET_PATH = 'GET_ASSET_PATH'
}
